apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glpi-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi
  labels:
    app: glpi
spec:
  selector:
    matchLabels:
      app: glpi
  replicas: 1 
  template: 
    metadata:
      labels:
        app: glpi
    spec:
      volumes:
      - name: glpi-data
        persistentVolumeClaim:
          claimName: glpi-data
      - name: socket
        emptyDir:
          # medium: memory
          sizeLimit: 100Mi
      hostname: glpi
      initContainers:
      - name: init
        image: localhost/glpi:10.0.17
        args:
        - /bin/sh
        - /init.sh
        env:
        - name: MARIADB_HOST
          value: "674aedef33c5"
        - name: MARIADB_USER
          value: "glpi"
        - name: MARIADB_PASSWORD
          value: "glpi"
          # valueFrom:
          #   secretKeyRef:
          #     name: glpi-mariadb
          #     key: mariadb-password
        - name: MARIADB_DATABASE
          value: "glpi"
        - name: GLPI_TELEMETRY
          value: "no"
        volumeMounts:
        - mountPath: /data
          name: glpi-data
      containers:
      - name: nginx
        image: localhost/glpi:10.0.17
        args:
        - /usr/sbin/nginx
        - -g
        - daemon off;
        ports:
        - containerPort: 80
          name: http
          hostPort: 8000  # Exposes container port 80 on host port 8000
        volumeMounts:
        - mountPath: /data
          name: glpi-data
        - mountPath: /run/php
          name: socket
        securityContext:
          capabilities:
            add: ["NET_BIND_SERVICE"]
      - name: php-fpm
        image: localhost/glpi:10.0.17
        args:
        - /usr/sbin/php-fpm83
        - -F
        volumeMounts:
        - mountPath: /data
          name: glpi-data
        - mountPath: /run/php
          name: socket
      - name: cron
        image: localhost/glpi:10.0.17
        args:
        - /usr/bin/supercronic
        - /etc/crontab-glpi
        volumeMounts:
        - mountPath: /data
          name: glpi-data
      securityContext:
        fsGroup: 101
