---
# Source: mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: glpi-mariadb
  labels:
    app.kubernetes.io/instance: glpi
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 11.6.2
type: Opaque
data:
  mariadb-root-password: "dVduakZQekFYTQ=="
  mariadb-password: "Z2xwaQ=="
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glpi-mariadb-data
  labels:
    app.kubernetes.io/instance: glpi
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: primary
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
# ---
# # Source: mariadb/templates/primary/svc.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: glpi-mariadb
#   labels:
#     app.kubernetes.io/instance: glpi
#     app.kubernetes.io/name: mariadb
#     app.kubernetes.io/version: 11.6.2
#   annotations:
# spec:
#   type: ClusterIP
#   sessionAffinity: None
#   ports:
#     - name: mysql
#       port: 3306
#       protocol: TCP
#       targetPort: mysql
#       nodePort: null
#   selector:
#     app.kubernetes.io/instance: glpi
#     app.kubernetes.io/name: mariadb
---
# Source: mariadb/templates/primary/statefulset.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi-mariadb
  labels:
    app.kubernetes.io/instance: glpi
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 11.6.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: glpi
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/part-of: mariadb
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: glpi
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/version: 11.6.2
    spec:
      # securityContext:
      #   fsGroup: 1001
      #   fsGroupChangePolicy: Always
      containers:
        - name: mariadb
          image: docker.io/library/mariadb:11.6.2
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   capabilities:
          #     drop:
          #     - ALL
          #   privileged: false
          #   readOnlyRootFilesystem: true
          #   runAsNonRoot: true
          #   seLinuxOptions: {}
          #   seccompProfile:
          #     type: RuntimeDefault
          env:
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "1"
            # - name: MARIADB_ROOT_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: glpi-mariadb
            #       key: mariadb-root-password
            - name: MARIADB_USER
              value: "glpi"
            - name: MARIADB_PASSWORD
              value: "glpi"
              # valueFrom:
              #   secretKeyRef:
              #     name: glpi-mariadb
              #     key: mariadb-password
            - name: MARIADB_DATABASE
              value: "glpi"
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: data
          persistentVolumeClaim:
            claimName: glpi-mariadb-data
