---
# Source: mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: glpi-mariadb
  labels:
    app.kubernetes.io/instance: glpi
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 11.6.2
type: Opaque
data:
  mariadb-root-password: "dVduakZQekFYTQ=="
  mariadb-password: "Z2xwaQ=="
