---
# helm template glpi oci://docker.io/bitnamicharts/mariadb -f .\mariadb-values.yaml

auth:
  database: glpi
  username: glpi
  existingPassword: glpi-mariadb   # (mariadb-root-password, mariadb-replication-password and mariadb-password)

primary:
  pdb:
    create: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/storage
            operator: In
            values:
              - "true"
initdbScripts:
  grantTZ: GRANT SELECT ON `mysql`.`time_zone_name` TO 'glpi'@'%';

networkPolicy:
  enabled: true
  allowExternal: false

serviceAccount:
  create: true
