---
# helm template glpi oci://docker.io/bitnamicharts/mariadb -f .\mariadb-values.yaml

auth:
  rootPasswrd: c,-kfa)tçTaQ)
  database: glpi
  username: glpi
  password: glpi
  # existingPassword: glpi-mariadb   # (mariadb-root-password, mariadb-replication-password and mariadb-password)


primary:
  pdb:
    create: false

networkPolicy:
  enabled: false
  ingressNSPodMatchLabels:
    app: glpi

serviceAccount:
  create: false